# docker-compose.yml
services:
  # Frontend Development
  frontend:
    image: node:20-alpine
    working_dir: /workspace/apps/web
    ports:
      - "5173:5173"
    volumes:
      # Mount entire monorepo
      - ./:/workspace
      # Exclude node_modules to avoid conflicts
      - /workspace/node_modules
      - /workspace/apps/web/node_modules
      - /workspace/apps/api/node_modules
      - /workspace/packages/config/node_modules
      - /workspace/packages/shared/node_modules
      - /workspace/packages/ui/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:3000/api
      - VITE_ENABLE_DEVTOOLS=true
    command: >
      sh -c "
        echo 'Installing pnpm...' &&
        npm install -g pnpm@10.12.4 &&
        cd /workspace &&
        echo 'Installing dependencies from root...' &&
        pnpm install &&
        cd /workspace/apps/web &&
        echo 'Starting Vite dev server...' &&
        pnpm dev --host 0.0.0.0
      "
    depends_on:
      - backend
    networks:
      - fanini-network
    restart: unless-stopped

  # Backend (Next.js API)
  backend:
    image: node:20-alpine
    working_dir: /workspace/apps/api
    ports:
      - "3000:3000"
    volumes:
      # Mount entire monorepo
      - ./:/workspace
        # Mount .env file
      - ./apps/api/.env:/workspace/apps/api/.env
      # Exclude node_modules
      - /workspace/node_modules
      - /workspace/apps/web/node_modules
      - /workspace/apps/api/node_modules
      - /workspace/packages/config/node_modules
      - /workspace/packages/shared/node_modules
      - /workspace/packages/ui/node_modules
    env_file:
      - ./apps/api/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://fanini:password@mysql:3306/fanini_db
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=fanini
      - DB_PASSWORD=password
      - DB_NAME=fanini_db
    command: >
      sh -c "
        echo 'Installing pnpm...' &&
        npm install -g pnpm@10.12.4 &&
        cd /workspace &&
        echo 'Installing dependencies from root...' &&
        pnpm install &&
        echo 'Waiting for database...' &&
        sleep 10 &&
        cd /workspace/apps/api &&
        echo 'Starting Next.js backend...' &&
        pnpm dev
      "
    depends_on:
      - mysql
    networks:
      - fanini-network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fanini_db
      MYSQL_USER: fanini
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - fanini-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: fanini
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - fanini-network

volumes:
  mysql_data:

networks:
  fanini-network:
    driver: bridge
