services:
  # Frontend Development - Fixed
  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api
      - VITE_ENABLE_DEVTOOLS=true
    command: >
      sh -c "
        echo 'Installing pnpm...' &&
        npm install -g pnpm@9.15.1 &&
        echo 'Installing dependencies...' &&
        pnpm install &&
        echo 'Starting Vite dev server...' &&
        pnpm dev --host 0.0.0.0
      "
    depends_on:
      - backend
    networks:
      - fanini-network
    restart: unless-stopped

  # Backend (für Phase 3)
  backend:
    image: node:20-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "echo 'Backend wird in Phase 3 implementiert' && sleep infinity"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://fanini:password@mysql:3306/fanini_db
    depends_on:
      - mysql
    networks:
      - fanini-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fanini_db
      MYSQL_USER: fanini
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - fanini-network

  # phpMyAdmin (für Entwicklung)
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: fanini
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - fanini-network

volumes:
  mysql_data:
  frontend_node_modules:

networks:
  fanini-network:
    driver: bridge
