packages:
  - "apps/*"
  - "packages/*"

ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
  - core-js
  - esbuild

onlyBuiltDependencies:
  - "@scarf/scarf"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "@tree-sitter-grammars/tree-sitter-yaml"
  - core-js-pure
  - esbuild
  - msw
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver
