packages:
  - frontend
  - backend
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - unrs-resolver
