#!/usr/bin/env sh
# Check if package.json was updated and run install
if git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD | grep --quiet "package.json\|pnpm-lock.yaml"; then
  echo "📦 Dependencies changed, running pnpm install..."
  pnpm install
fi
